main: de.d3rhase.BlockLocationTrackerPlugin
name: 'BlockLocationTracker'
version: 1.2
api-version: 1.20
commands:
  blt:
    description: Toggles block highlighting and manages block list.
    usage: "/blt <showblocks> <true|false>"
